spring:
  application:
    name: springboot-mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=no
    username: root
    password: Bring952480??